---
# Source: nqueen/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nqueen-config
data:
  APP_UID: "1000"
---
# Source: nqueen/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nqueen-service
spec:
  selector:
    app: nqueen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Source: nqueen/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nqueen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nqueen
  template:
    metadata:
      labels:
        app: nqueen
    spec:
      containers:
        - name: nqueen
          image: "nqueen-app:latest"
          imagePullPolicy: IfNotPresent
          args: ["4", "5"]
          env:
            - name: APP_UID
              value: "1000"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
